name: tonic
version: 0.2.3

description: >
  Classes and methods for representing and manipulating concepts from music theory:
  Pitch, PitchClass, Interval, Scale, Chord.
authors:
- Oliver Steele <steele@osteele.com>
- Rody Davis <rody.davis.jr@gmail.com>
homepage: http://github.com/osteele/dart-tonic
documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.8
